import { motion } from "motion/react";
import { PlayCircle, Video, ChevronDown } from "lucide-react";

export default function Gallery() {
  const categories = ["All Work", "Clubs", "Concerts", "Mapping", "Logos", "Behind the Scenes"];

  const projects = [
    { id: 1, category: "Concert Visuals", title: "System Overload 01", image: "https://picsum.photos/seed/sys/800/1000", aspect: "aspect-[4/5]" },
    { id: 2, category: "Mapping", title: "Brutalist Echo", image: "https://picsum.photos/seed/brut/800/450", aspect: "aspect-video" },
    { id: 3, category: "Plugin R&D", title: "Fragmented Core", image: "https://picsum.photos/seed/frag/800/1200", aspect: "aspect-[2/3]" },
    { id: 4, category: "Clubs", title: "Afterlife Berlin", image: "https://picsum.photos/seed/berlin/800/800", aspect: "aspect-square" },
    { id: 5, category: "Logos", title: "Identity Morph", image: "https://picsum.photos/seed/morph/800/1066", aspect: "aspect-[3/4]" },
    { id: 6, category: "Concerts", title: "Mainstage 2024", image: "https://picsum.photos/seed/main/800/450", aspect: "aspect-video", video: true },
  ];

  return (
    <main className="pt-32 pb-20 px-6 md:px-12 max-w-[1600px] mx-auto">
      {/* Hero Section */}
      <section className="mb-16">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-8">
          <div>
            <h1 className="text-6xl md:text-8xl font-headline font-black tracking-tighter uppercase leading-[0.9] text-white">
              Visual<br /><span className="text-secondary">Intelligence</span>
            </h1>
            <p className="mt-6 text-on-surface-variant max-w-xl font-body text-lg leading-relaxed">
              A curated archive of immersive digital environments, motion experiments, and live performance data generated by the INNSAEI collective.
            </p>
          </div>
          <div className="flex items-center gap-4">
            <div className="w-2 h-2 bg-secondary animate-pulse"></div>
            <span className="font-headline text-xs tracking-[0.3em] uppercase text-on-surface-variant">Live Feed Active</span>
          </div>
        </div>
      </section>

      {/* Filter Bar */}
      <div className="flex flex-wrap items-center gap-4 mb-12 border-b border-white/5 pb-8">
        {categories.map((cat, i) => (
          <button
            key={cat}
            className={`px-6 py-2 font-headline text-xs tracking-widest uppercase transition-all ${
              i === 0
                ? "bg-secondary text-white"
                : "bg-surface-container-lowest border border-white/10 text-on-surface-variant hover:text-white hover:border-secondary"
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Masonry-like Grid */}
      <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
        {projects.map((project) => (
          <motion.div
            key={project.id}
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="group relative overflow-hidden bg-surface-container-lowest cursor-pointer break-inside-avoid"
          >
            <div className={project.aspect}>
              <img
                src={project.image}
                alt={project.title}
                className="object-cover w-full h-full grayscale hover:grayscale-0 transition-all duration-700 scale-105 group-hover:scale-100"
                referrerPolicy="no-referrer"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent opacity-80"></div>
              <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                {project.video ? (
                  <Video className="text-white" size={48} />
                ) : (
                  <PlayCircle className="text-white" size={48} />
                )}
              </div>
            </div>
            <div className="absolute bottom-0 left-0 p-6 w-full translate-y-4 group-hover:translate-y-0 transition-transform duration-500">
              <span className="text-[10px] tracking-[0.4em] uppercase text-secondary font-headline mb-2 block">
                {project.category}
              </span>
              <h3 className="text-xl font-headline font-bold text-white uppercase tracking-tight">
                {project.title}
              </h3>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Load More */}
      <div className="mt-20 flex flex-col items-center">
        <div className="w-px h-24 bg-gradient-to-b from-secondary to-transparent mb-8"></div>
        <button className="group flex flex-col items-center gap-4">
          <span className="font-headline text-[10px] tracking-[0.6em] uppercase text-on-surface-variant group-hover:text-white transition-colors">
            Expand Archive
          </span>
          <ChevronDown className="text-white animate-bounce" size={24} />
        </button>
      </div>
    </main>
  );
}
